language: node_js
node_js:
- '5'
addons:
  code_climate:
    repo_token: <REPO TOKEN GOES HERE>
before_script:
  - npm install -g codeclimate-test-reporter
after_script:
- codeclimate-test-reporter < coverage/lcov.info
deploy:
  provider: npm
  email: serveradmin@octoblu.com
  api_key:
  on:
    tags: true
    branches: true
